apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  secretStoreRef:
    name: my-secret-store
    kind: SecretStore

  target:
    name: my-kubernetes-secret

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/db
